# This file was generated by GoReleaser. DO NOT EDIT.
cask "fox" do
  version "4.46.1"

  on_macos do
    on_intel do
      sha256 "c8fecca2d55331c0c304701322cac8b7d040edcd340d931f956bd9461cbfc25b"
      url "https://github.com/f0x4n6/fox/releases/download/v#{version}/fox_darwin_amd64.tar.gz",
        verified: "github.com/f0x4n6/fox-cask/"
    end
    on_arm do
      sha256 "c895765274e5157ec476ccc9b84ffabed71c862daace8ef34072734711b0e84d"
      url "https://github.com/f0x4n6/fox/releases/download/v#{version}/fox_darwin_arm64.tar.gz",
        verified: "github.com/f0x4n6/fox-cask/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ba42bcf334d496471beb0443576eda639fde6218b2e3f1ca7399b1905f6de1ef"
      url "https://github.com/f0x4n6/fox/releases/download/v#{version}/fox_linux_amd64.tar.gz",
        verified: "github.com/f0x4n6/fox-cask/"
    end
    on_arm do
      sha256 "d88313c3ad64000be02c51a09ed90eea85082e7ece12c76e8466c231d65fa982"
      url "https://github.com/f0x4n6/fox/releases/download/v#{version}/fox_linux_arm64.tar.gz",
        verified: "github.com/f0x4n6/fox-cask/"
    end
  end

  name "fox"
  desc "The Forensic Examiners Swiss Army Knife"
  homepage "https://foxforensics.eu/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fox"
  manpage "fox-dump.1"
  manpage "fox-hash.1"
  manpage "fox-hunt.1"
  manpage "fox-info.1"
  manpage "fox-str.1"
  manpage "fox.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fox"]
    end
  end

  # No zap stanza required

end
