# This file was generated by GoReleaser. DO NOT EDIT.
cask "fox" do
  version "4.49.0"

  on_macos do
    on_intel do
      sha256 "f992cc9d588c627528e8c9e5c149abcf91356034f009ea712469283e01ea8ef2"
      url "https://github.com/f0x4n6/fox/releases/download/v#{version}/fox_darwin_amd64.tar.gz",
        verified: "github.com/f0x4n6/fox-cask/"
    end
    on_arm do
      sha256 "a91bedb531288841c8ab9fd811cc7dd153b615ecec05c4bc52b66d6c2d76a603"
      url "https://github.com/f0x4n6/fox/releases/download/v#{version}/fox_darwin_arm64.tar.gz",
        verified: "github.com/f0x4n6/fox-cask/"
    end
  end

  on_linux do
    on_intel do
      sha256 "45152cf6a1798f4b98b9f524a93ae29e1043ae5d42b6348903339606d3e5dad6"
      url "https://github.com/f0x4n6/fox/releases/download/v#{version}/fox_linux_amd64.tar.gz",
        verified: "github.com/f0x4n6/fox-cask/"
    end
    on_arm do
      sha256 "2135f3480315a17537b3c27ba4ea6d3aab9066b730858fb759fa75c5db2fdb43"
      url "https://github.com/f0x4n6/fox/releases/download/v#{version}/fox_linux_arm64.tar.gz",
        verified: "github.com/f0x4n6/fox-cask/"
    end
  end

  name "fox"
  desc "The Forensic Examiners Swiss Army Knife"
  homepage "https://foxforensics.eu/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fox"
  manpage "fox-ad.1"
  manpage "fox-hash.1"
  manpage "fox-hunt.1"
  manpage "fox-info.1"
  manpage "fox-str.1"
  manpage "fox.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fox"]
    end
  end

  # No zap stanza required

end
